before_script:
  - mysql -e 'create database activeuuid_test;'
  - psql -c 'create database activeuuid_test;' -U postgres

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - rbx-2

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3-1
  - gemfiles/Gemfile.rails-3-2
  - gemfiles/Gemfile.rails-4-0
  - gemfiles/Gemfile.rails-4-1
  - gemfiles/Gemfile.rails-4-2
  - gemfiles/Gemfile.rails-head

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3-1
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3-2
